FROM debian

ADD https://storage.googleapis.com/kubernetes-helm/helm-v2.2.0-linux-amd64.tar.gz /opt/helm/

ENV HELM_HOME /root/.helm

RUN tar xf /opt/helm/helm-v2.2.0-linux-amd64.tar.gz -C /opt/helm/ && mv /opt/helm/linux-amd64/helm /usr/bin/ && rm -R /opt/helm/
RUN helm init --client-only && mkdir -p $HELM_HOME/plugins/template/
RUN wget -qO helm-template.tar.gz https://github.com/technosophos/helm-template/releases/download/2.1.3%2B1/helm-template-linux.tgz
RUN tar xf helm-template.tar.gz -C $HELM_HOME/plugins/template/
